
#define _GNU_SOURCE
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <unistd.h>
#include <stdarg.h>
#include <getopt.h>
#include <string.h>
#include <signal.h>
#include <pthread.h>
#include <arpa/inet.h>
#include <sys/prctl.h>
#include <sched.h>
#include <sys/sysinfo.h>
#include <regex.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <errno.h>